In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [2]:
X_train = pd.read_csv("X_train_processed.csv")
X_test = pd.read_csv("X_test_processed.csv")

y_train = pd.read_csv("y_train.csv").values.ravel()
y_test = pd.read_csv("y_test.csv").values.ravel()

X_train.shape, X_test.shape

((3278, 19), (820, 19))

In [3]:
X_train.head()
np.unique(y_train)

array(['At_Risk', 'Malnourished', 'Normal'], dtype=object)

In [4]:
log_reg = LogisticRegression(
    max_iter=1000,
    multi_class="auto",
    random_state=42
)

In [5]:
log_reg.fit(X_train, y_train)

C:\Users\Bluebrand_pvt_ltd\Documents\FL\Local-ML-Client\Project_Private\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(max_iter=1000, multi_class='auto', random_state=42)

In [6]:
log_reg.coef_.shape

(3, 19)

In [7]:
y_pred_lr = log_reg.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:\n", classification_report(y_test, y_pred_lr))

Accuracy: 0.4951219512195122

Classification Report:
               precision    recall  f1-score   support

     At_Risk       0.00      0.00      0.00       248
Malnourished       0.00      0.00      0.00       166
      Normal       0.50      1.00      0.66       406

    accuracy                           0.50       820
   macro avg       0.17      0.33      0.22       820
weighted avg       0.25      0.50      0.33       820

C:\Users\Bluebrand_pvt_ltd\Documents\FL\Local-ML-Client\Project_Private\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Bluebrand_pvt_ltd\Documents\FL\Local-ML-Client\Project_Private\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Bluebrand_pvt_ltd\Documents\FL\Local-ML-Client\Project_Private\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [8]:
confusion_matrix(y_test, y_pred_lr)

array([[  0,   0, 248],
       [  0,   0, 166],
       [  0,   0, 406]])

In [9]:
dt = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

In [10]:
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [11]:
dt.get_depth()

5

In [12]:
y_pred_dt = dt.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))

Accuracy: 0.49146341463414633

Classification Report:
               precision    recall  f1-score   support

     At_Risk       0.37      0.03      0.05       248
Malnourished       0.31      0.02      0.04       166
      Normal       0.50      0.97      0.66       406

    accuracy                           0.49       820
   macro avg       0.39      0.34      0.25       820
weighted avg       0.42      0.49      0.35       820

In [13]:
baseline_results = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_dt)
    ]
})

baseline_results

                 Model  Accuracy
0  Logistic Regression  0.495122
1        Decision Tree  0.491463

In [14]:
# Check class balance
pd.Series(y_train).value_counts(normalize=True)

# Check prediction distribution
pd.Series(y_pred_lr).value_counts()
pd.Series(y_pred_dt).value_counts()

Normal          788
At_Risk          19
Malnourished     13
Name: count, dtype: int64

In [15]:
log_reg_bal = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    multi_class="auto",
    random_state=42
)

In [16]:
log_reg_bal

LogisticRegression(class_weight='balanced', max_iter=1000, multi_class='auto',
                   random_state=42)

In [17]:
log_reg_bal.fit(X_train, y_train)

C:\Users\Bluebrand_pvt_ltd\Documents\FL\Local-ML-Client\Project_Private\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(class_weight='balanced', max_iter=1000, multi_class='auto',
                   random_state=42)

In [18]:
log_reg_bal.coef_.shape

(3, 19)

In [19]:
y_pred_lr_bal = log_reg_bal.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lr_bal))
print("\nClassification Report:\n", classification_report(y_test, y_pred_lr_bal))

Accuracy: 0.31341463414634146

Classification Report:
               precision    recall  f1-score   support

     At_Risk       0.28      0.33      0.30       248
Malnourished       0.18      0.29      0.22       166
      Normal       0.48      0.31      0.38       406

    accuracy                           0.31       820
   macro avg       0.31      0.31      0.30       820
weighted avg       0.36      0.31      0.32       820

In [20]:
pd.Series(y_pred_lr_bal).value_counts()

At_Risk         292
Normal          264
Malnourished    264
Name: count, dtype: int64

In [21]:
dt_bal = DecisionTreeClassifier(
    max_depth=5,
    class_weight="balanced",
    random_state=42
)

In [22]:
dt_bal.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42)

In [23]:
dt_bal.get_depth()

5

In [24]:
y_pred_dt_bal = dt_bal.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_dt_bal))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt_bal))

Accuracy: 0.28780487804878047

Classification Report:
               precision    recall  f1-score   support

     At_Risk       0.27      0.46      0.34       248
Malnourished       0.20      0.30      0.24       166
      Normal       0.47      0.18      0.26       406

    accuracy                           0.29       820
   macro avg       0.31      0.31      0.28       820
weighted avg       0.36      0.29      0.28       820

In [25]:
baseline_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Logistic Regression (Balanced)",
        "Decision Tree",
        "Decision Tree (Balanced)"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_lr_bal),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_dt_bal)
    ]
})

baseline_comparison

                            Model  Accuracy
0             Logistic Regression  0.495122
1  Logistic Regression (Balanced)  0.313415
2                   Decision Tree  0.491463
3        Decision Tree (Balanced)  0.287805

In [26]:
from sklearn.metrics import recall_score

print("Recall (Malnourished):")
print("LR:", recall_score(y_test, y_pred_lr, labels=["Malnourished"], average=None))
print("LR Balanced:", recall_score(y_test, y_pred_lr_bal, labels=["Malnourished"], average=None))
print("DT:", recall_score(y_test, y_pred_dt, labels=["Malnourished"], average=None))
print("DT Balanced:", recall_score(y_test, y_pred_dt_bal, labels=["Malnourished"], average=None))

Recall (Malnourished):
LR: [0.]
LR Balanced: [0.28915663]
DT: [0.02409639]
DT Balanced: [0.30120482]